services:
  - type: web
    name: ml-fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8080
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
